# Generated by Django 5.2.12 on 2026-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
