# Generated by Django 5.2.12 on 2026-04-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_smtpconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='smtp_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='mailer.smtpconnection'),
        ),
    ]
