# Generated by Django 5.2.12 on 2026-04-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_emailbatch_smtp_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbatch',
            name='gmail_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='mailer.gmailconnection'),
        ),
    ]
